version: '3'
services:
  mysql:
    container_name: mysql-course
    image: mysql:5.6.35
    network_mode: host
    restart: 'always'
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coursejdbc
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

